### ISSUE TITLE
client.Close hangs on channel recvClosed

### ISSUE THREAD

**Issue by rlmcpherson** [pkg/sftp#42] opened 2015-06-11 16:04 UTC
When closing clients that are accessed concurrently from multiple goroutines, the client `Close()` method hangs waiting on a receive from c.recvClosed. This started occurring when a change was made in the client code to use clients concurrently from more than one goroutine. I suspect there is a deadlock occurring in the client `recv()` function, since this is the only  function that closes the `c.recvClosed` channel. Requests may still be in progress when client `Close` is called, but this shouldn't cause the method to block indefinitely. I think the `Close()` method may need a way to cancel inflight requests. I'm happy to take a stab at a PR or do additional debugging on this but if anyone with more familiarity with the sftp package code  can comment on why this is occurring I'd appreciate it. 

partial stacktrace showing blocking on `recvClosed`:
```
goroutine 5 [chan receive, 1013 minutes]:
github.com/pkg/sftp.(*Client).Close(0xc25d62f590, 0x0, 0x0)
        /Users/rmcpherson/dev/go/src/github.com/pkg/sftp/client.go:100 +0x8d
github.com/codeguard/lister/client.(*SftpClient).Close(0xc208945e60, 0x0, 0x0)
```

**Comment by davecheney** [comment] 2015-06-12 06:15
Oh crap, this was what I was afraid of (we went through a lot of these issues in the ssh pacakge). I'll take a look this weekend, /cc @ggriffiniii

**Comment by ggriffiniii** [comment] 2015-06-12 16:22
Can you provide the full stack trace. The Close() previously only shutdown it's end of the connection, now it shuts down it's end and waits for the server to shut down the other end. If the recv() goroutine is still blocked on reading then the server hasn't shutdown yet and that's why it's blocked. If the recv() goroutine is stuck doing something else then some of the constraints are being violated and I would need to double check my logic.

**Comment by rlmcpherson** [comment] 2015-06-12 16:48
@ggriffiniii I didn't save the full stack trace but I can try to reproduce it and send the stack traces that include the sftp package. It seems like the client be able to close without necessarily waiting for all requests made to the server to complete. Instead, the client should send SSH_FXP_CLOSE according to the spec. (https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-6.7 "When the client no longer wishes to read more names from the directory, it SHOULD call SSH_FXP_CLOSE for the handle." /cc @davecheney

**Comment by ggriffiniii** [comment] 2015-06-12 19:01
Minor point, it's not technically waiting for all requests from the server to be fulfilled. It's waiting for the server to close it's end of the connection, which the server may elect to do without responding to all inflight requests. In fact I believe that's what openssh's sftp-server does. As soon as the sftp-server reads EOF it exits without writing it's output buffer or finishing any in-progress requests.

While I can see the desire to have a client that's able to close without waiting for the server, I'm not quite sure how that can be accomplished. This differs from a typical net.Conn connection because net.Conn has help from the runtime so that net.Conn.Close() unblocks any readers of the file descriptor. Meaning that the runtime is able to signal to the reader that it's reached EOF. In our case we are given an io.Reader and an io.WriteCloser. Meaning that the only direct action we can take on Close() is to close the write end of the connection, we then must wait for the read end of the connection to be closed to avoid any data races in subsequent uses of the Reader by any non-sftp code.

One possible solution is to provide a Close() which simply closes the write end of the connection, and a Wait() that waits for the read end of the connection. Then users could elect to Close() without waiting and still provide a synchronization point for users that want to know when both ends of the connection are fully closed. This doesn't seem particularly clean, but it would allow us to avoid the data race in the integration tests (which only happens when spawning sftp server locally not when using a *ssh.Client) while still providing what most users want/expect.

**Comment by ggriffiniii** [comment] 2015-06-12 19:22
I'm not entirely convinced this is necessary or the best way to do it, but I prepared pull request #43 to add a Wait() method and updated the integration tests accordingly.

**Comment by davecheney** [comment] 2015-06-15 09:15
Thanks for taking a look but the fix in #43 does not look right. As I understand it the server is dropping the session, it seems like we can detect that.

@rlmcpherson can you assure us that there are no data races reported in your program ?

**Comment by davecheney** [comment] 2015-06-15 09:20
@ggriffiniii I think this bug is unrelated to `Close`. As a test I ran `streaming-read-benchmark` from the examples directory, then while it was running, killed the sftp-sever child process, no error was returned on the client side.

**Comment by davecheney** [comment] 2015-06-15 09:21
```
goroutine 19 [chan send (nil chan)]:
github.com/pkg/sftp.(*Client).broadcastErr(0xc2080b0be0, 0x7f6e1f366028, 0xc20800e170)
        /home/dfc/src/github.com/pkg/sftp/client.go:150 +0x23b
github.com/pkg/sftp.(*Client).recv(0xc2080b0be0)
        /home/dfc/src/github.com/pkg/sftp/client.go:162 +0xe4
created by github.com/pkg/sftp.NewClientPipe
        /home/dfc/src/github.com/pkg/sftp/client.go:76 +0x2d6
```

I think the problem is a nil channel has been passed to `broadcastErr`

**Comment by davecheney** [comment] 2015-06-15 09:23
Found the bug. Fix coming shortly.

**Comment by ggriffiniii** [comment] 2015-06-15 15:50
Stupid mistake. Thanks for the fix.

**Comment by rlmcpherson** [comment] 2015-06-15 16:04
@davecheney Thanks for the fix! I retested with it and everything seems to be working correctly now.

**Closed** 2015-06-15 21:04 UTC
Labels: bug

**Comment by davecheney** [comment] 2015-06-15 21:50
@ggriffiniii don't worry about it, it was my mistake for missing it in the review. It is a reminder (again) for me to _always_ check that that the slice has a cap, not a length, when using that preallocated form.
