### ISSUE TITLE
get error "internal inconsistency" when use "WriteTo"

### ISSUE THREAD

**Issue by FateTHarlaown** [pkg/sftp#322] opened 2019-11-19 15:26 UTC
I use  `WriteTo`  function to download a file from a remote server, the code like this
```
func (ft *fileTransfer) Get(localPath, remotePath string) error {
	srcFile, err := ft.sftpClient.Open(remotePath)
	if err != nil {
		return err
	}
	defer srcFile.Close()

	dstFile, err := os.Create(localPath)
	if err != nil {
		return err
	}
	defer dstFile.Close()

	_, err = srcFile.WriteTo(dstFile)

	return err
}
```
Most of time, it works well , but I once got an error `"internal inconsistency"`  and I can't repeat it. The document said maybe it  was caused by server side
```
// InternalInconsistency indicates the packets sent and the data queued to be
// written to the file don't match up. It is an unusual error and usually is
// caused by bad behavior server side or connection issues. The error is
// limited in scope to the call where it happened, the client object is still
// OK to use as long as the connection is still open.
var InternalInconsistency = errors.New("internal inconsistency")
```
Can I know the reason and the way to avoid it?

**Comment by puellanivis** [comment] 2019-11-21 17:21
If you’ve only gotten it once, and find it difficult to repeat, it’s most likely a random bitflip error. Stray cosmic ray, decaying memory, or something like that.

I’d say make a wish, because you got lucky to hit it. :laughing:

**Comment by FateTHarlaown** [comment] 2019-11-22 13:33
@puellanivis Thanks......I should probably buy a lottery ticket and make a wish. And I plan to donate for this project when I get millions of dollars....lol.
On the orther hand, If I find a way to repeat I will report it to you.

>

**Comment by eikenb** [comment] 2019-11-28 19:15
Thanks for the report/question @FateTHarlaown. I'm going to close this as unreproducable, but if you ever figure out a way to reproduce this please let us know in a new ticket.

**Closed by eikenb** 2019-11-28 19:15 UTC
Labels: question
