### ISSUE TITLE
The file upload hangs when the VPN server is disconnected.

### ISSUE THREAD

**Issue by dwlpra** [pkg/sftp#540] opened 2023-02-22 16:19 UTC
I am having an issue when sending files to SFTP. When the internet disconnects, the file transfer will resume when not all files have been sent. However, when the VPN to access the server disconnects, the file transfer will hang and cause the program to stop sending files. I have no clue on how to solve this. I have tried using an infinite loop to open a new connection when the internet disconnects, and it works. But when the VPN disconnects, it really makes the program hang

**Comment by drakkan** [comment] 2023-02-22 16:25
duplicate of #502

**Closed** 2023-02-22 16:25 UTC
