### ISSUE TITLE
io.Copy with sftp.File destination results in early termination

### ISSUE THREAD

**Issue by binary132** [pkg/sftp#180] opened 2017-04-29 05:24 UTC
Hello,

This issue was observed on Fedora Linux (EL7) using Go1.7.4 amd64.

After copying other local files to an SFTP server in a loop, the last file in the sequence reproducibly fails with the following behavior.  I'm still investigating.

I got `"failed to send packet header: EOF"` on sftp.File Close, after using `io.Copy` with a freshly created `sftp.File` as the destination, and a freshly-opened, non-empty `os.File` as the read source.  I suspect this has something to do with the implementation of `sftp.File.ReaderFrom`, since `os.File` does not implement `io.WriterTo`. (Ex. 1)

I was able to resolve this using the copy loop from `io.Copy` not including the type coercion (Ex. 2).

Another strange effect was that if I used `bufio.Writer` over `sftp.File` as my copy target, even using the stripped-down copy loop, it had a similar error on Flush. (Ex. 3)

Hopefully you have some insight, as I am stumped.  Fortunately the copy-loop workaround with no bufio.Writer is working for me.  It is entirely possible that you will be unable to reproduce this.

I will reply to this thread if I discover something new.

---

Ex. 1 -- io.Copy problem ([Source of error](https://github.com/pkg/sftp/blob/94df0a367c78a139a5351d2a3ec204b61170ded9/packet.go#L132) linked.)

```go
f, _ := os.Open("foo")
sf, _ := client.Create("/remote/bar")
ct, _ := io.Copy(sf, f)
panic(sf.Close()) // should be `"failed to send packet header: EOF"`.
```

---

Ex. 2 -- using custom copy to avoid problem

```go
f, _ := os.Open("foo")
sf, _ := client.Create("/remote/bar")
buf := make([]byte, 32*1024)
ct, _ := customCopy(sf, f, buf)
log.Println(sf.Close()) // should be nil.

// customCopy implements the buffered io.Copy loop without the WriterTo
// or ReaderFrom interface checks.
func customCopy(dst io.Writer, src io.Reader, buf []byte) (count int64, err error) {
	for {
		nr, er := src.Read(buf)
		if nr > 0 {
			nw, ew := dst.Write(buf[0:nr])
			if nw > 0 {
				count += int64(nw)
			}
			if ew != nil {
				err = ew
				break
			}
			if nr != nw {
				err = io.ErrShortWrite
				break
			}
		}
		if er != nil {
			if er != io.EOF {
				err = er
			}
			break
		}
	}
	return count, err
}
```

---

Ex. 3 -- buffered write fails

```go
f, _ := os.Open("foo")
sf, _ := client.Create("/remote/bar")
sfBuf := bufio.NewWriter(sfBuf, 4*(1<<20))
buf := make([]byte, 32*1024)
ct, _ := customCopy(sfBuf, f, buf)
panic(sfBuf.Flush()) // should be similar packet header write EOF.
```

**Comment by eikenb** [comment] 2017-04-29 22:04
What was the SFTP server you were uploading to?
Have you tried reproducing it with an alternative server?

**Comment by eikenb** [comment] 2017-05-03 19:26
I cannot reproduce this with either the OpenSSH SFTP server nor the example SFTP server included with this library. I looped through 46 smaller text files copying them using the built in copy (like in your first example) and it worked fine.

At this point is seems it must be related to the server you are using.

**Comment by binary132** [comment] 2017-05-04 14:08
Ok.  I'll follow up with more details as I get them.  Thanks for checking. 👍

**Comment by eikenb** [comment] 2017-07-23 19:47
@binary132  Did you happen to be setting the max packet size in your NewClient call?

	client, err := sftp.NewClient(sshConn, sftp.MaxPacket(262119))

In #185 they also received this EOF error andthe cause was setting MaxPacket size to a large value. Turns out anything > 262119 will trigger an error on upload. Though this was only with larger files, the reporter said >300K triggered it.

**Comment by binary132** [comment] 2017-07-25 21:26
Yes.  The max packet size is set to 262144 (`1<<18`.)  Big thanks for following up!

**Comment by eikenb** [comment] 2017-07-26 02:57
Closing as a duplicate of #185

**Closed by eikenb** 2017-07-26 02:57 UTC
Labels: bug, duplicate
