### ISSUE TITLE
internal inconsistency

### ISSUE THREAD

**Issue by wmtdpl** [pkg/sftp#327] opened 2019-12-23 13:16 UTC
Download file from sftp 1.10.1, appear this：
ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [**diffie-hellman-group-exchange-sha256**]

I add the KeyExchange to ClientConfig
                sshconfig := ssh.Config{}
		sshconfig.SetDefaults()
		sshconfig.KeyExchanges = append(
			sshconfig.KeyExchanges,
			"diffie-hellman-group-exchange-sha256",
			"diffie-hellman-group-exchange-sha1",
		)

		configTmp := &ssh.ClientConfig{
			Config: sshconfig,
			User: client.User,
			Auth: []ssh.AuthMethod{
				ssh.Password(client.Password),
			},
			HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		}
Then an error message appears：internal inconsistency
I found that the size of maxpacket is 1 << 15（322768）,  but the downloaded file size is 32769， In fact, the file size is greater than 32769. It seems that only one package has been downloaded.
Is there a way to solve this problem? 
thanks

**Comment by eikenb** [comment] 2019-12-30 20:37
This problem is due to an upstream bug in the x/crypto/ssh library for which I've already filed a bug https://github.com/golang/go/issues/32075. I'm closing this as a duplicate of the issue that had me file the upstream issue, #287.

**Closed by eikenb** 2019-12-30 20:37 UTC
Labels: duplicate
