### ISSUE TITLE
clientConn.Close() hangs when Client.Lstat() got an EOF error

### ISSUE THREAD

**Issue by xiu** [pkg/sftp#167] opened 2017-03-01 13:23 UTC
# Versions
- Go 1.8
- pkg/sftp 94df0a367c78a139a5351d2a3ec204b61170ded9
- remote server: Serv-U 15.1.3.3

# Issue
The EOF error is returned on the following:
`info, err := client.Lstat(file)`

Error returned:
`failed to send packet header: EOF`

The function that got the error then returns and executes the following:
`defer client.Close()`

Which hangs:
```
goroutine 152 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc4204012fc)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4204012f0)
        /usr/local/Cellar/go/1.8/libexec/src/sync/waitgroup.go:131 +0x7a
bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp.(*clientConn).Close(0xc4204012c0, 0x7d8ba0, 0xc4200120f0)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp/conn.go:44 +0x8b
main.(*SFTPRemote).Loader.func2(0xc42021af10, 0x1, 0xc4204012c0)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/src/sftp.go:530 +0xe8
main.(*SFTPRemote).Loader(0xc42021af10, 0x1, 0xc42021b000)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/src/sftp.go:591 +0x11c4
created by main.(*SFTPRemote).Walkthrough
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/src/sftp.go:306 +0x6ac

goroutine 162 [chan send, 3 minutes]:
bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp.(*clientConn).broadcastErr(0xc4204012c0, 0x7d8ba0, 0xc4200120f0)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp/conn.go:121 +0x272
bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp.(*clientConn).loop(0xc4204012c0)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp/conn.go:51 +0x92
created by bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp.NewClientPipe
        Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/vendor/github.com/pkg/sftp/client.go:77 +0x20c
```

It seems that there has been an issue in the past where clientConn.Close() hung, see #42.

**Comment by xiu** [comment] 2017-03-06 12:19
I was able to reproduce the issue with the following code:
```
package main

import (
	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
	"log"
	"bytes"
	"io"
	"os"
	"os/signal"
	"syscall"
	"runtime"
)

var (
	HOST="10.0.30.133"
	LOGIN="test"
	PASSWORD="test"

	AUTH []ssh.AuthMethod
)

func main() {
	AUTH = append(AUTH, ssh.Password(PASSWORD))

	config := ssh.ClientConfig{
		User: LOGIN,
		Auth: AUTH,
	}

	sshclient, err := ssh.Dial("tcp", HOST+":22", &config)
	if err != nil {
		panic(err)
	}

	sftpclient, err := sftp.NewClient(sshclient)
	if err != nil {
		panic(err)
	}

	walker := sftpclient.Walk("/download/big/")
	for {
		if !walker.Step() {
			// we're at the end of the walk, exiting the for loop
			log.Println("!walker.Step()")
			break
		}
		if walker.Err() != nil {
			log.Println("walker.Err()")
			break
		}

		info := walker.Stat()

		if !info.IsDir() {
			file := walker.Path()

			_, err := sftpclient.Lstat(file)
			if err != nil {
				log.Printf("First Lstat: %s", err.Error())
			}

			src, err := sftpclient.Open(file)
			if err != nil {
				log.Printf("Open: %s", err.Error())
			}

			// download file
			fileBuf := &bytes.Buffer{}
			_, err = io.Copy(fileBuf, src)
			if err != nil {
				log.Printf("io.Copy: %s", err.Error())
				break
			}
			src.Close()

			_, err = sftpclient.Lstat(file)
			if err != nil {
				log.Printf("Second Lstat: %s", err.Error())
				break
			}
		}
	}

	sftpclient.Close()
	sshclient.Close()
}
```

The remote server is Serv-U 15.1.5 with the default settings. In /download/big/ there are 3 1G files. It usually crashes on the first io.Copy or on the second Lstat. It will then hang on sftpclient.Close()

**Comment by xiu** [comment] 2017-03-07 13:59
It seems that when I hit an EOF on the second Lstat, I still have a lot of inflight queries (clientConn.inflight). Not sure how that would be possible as the transfer (io.Copy) has been finished. 

If needed to debug further I'm on freenode.

**Comment by xiu** [comment] 2017-03-15 08:44
@eikenb any idea on how to fix that one?

**Comment by xiu** [comment] 2017-03-16 09:43
No problem, let me know how I can help, couldn't find a way to fix that yet

**Comment by eikenb** [comment] 2017-04-19 18:36
I've tried your code against both the server implemented in this library as well as against openssh's sftp server and was unable to reproduce it. I used 3 1G files as in your test.

I'm left with the probably conclusion that there is some poor interaction between the client code and the Serv-U sftp server. Have you reproduced this against any other sftp server?

**Comment by eikenb** [comment] 2017-04-19 18:46
I'm also curious if you have tried this again recently? In your error/traceback the first goroutine was waiting on a lock when it crashed. The code around that lock changed a bit and might have changed that behavior.

**Comment by xiu** [comment] 2017-04-20 16:00
Yes I was under the same impression that the problem is the interaction between Serv-U and the client code. I tried again with the latest version and I still end up with the same issue. 

As I understand it the only fix that has been done around that lock is 506f3a7848764bb32e66db7f517284c7dcd3a1f2. I tried to debug further and see the same behavior: a lot of inflight queries on which broadcastError tries to send a result struct.

Here's a new stacktrace:
```
2017/04/20 17:57:42 src.Close(): failed to send packet header: EOF
2017/04/20 17:57:42 Second Lstat: failed to send packet header: EOF
SIGABRT: abort
PC=0x1054feb m=0 sigcode=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0xf03, 0x0, 0x0, 0x0, 0x1295ec0, 0x1295ec0, 0x7fff5fbff5f8, 0x104f833, 0xffffffffffffffff, 0x7fff00000000, ...)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/sys_darwin_amd64.s:415 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x7fff00000000)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/os_darwin.go:413 +0x4b
runtime.semasleep.func1()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/os_darwin.go:432 +0x33
runtime.systemstack(0x7fff5fbff620)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:343 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/os_darwin.go:433 +0x4d
runtime.notesleep(0x1296330)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/lock_sema.go:166 +0xb2
runtime.stopm()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc42001c000, 0x0)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/proc.go:2222 +0x14c
runtime.goexit0(0xc420090d00)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/proc.go:2359 +0x238
runtime.mcall(0x7fff5fbff7f0)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42007275c)
        /usr/local/Cellar/go/1.8/libexec/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc420072750)
        /usr/local/Cellar/go/1.8/libexec/src/sync/waitgroup.go:131 +0x7a
bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp.(*clientConn).Close(0xc420072720, 0x127d880, 0xc4200100e0)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp/conn.go:44 +0x8b
main.main()
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/167/main.go:84 +0x4a9

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197 +0x1

goroutine 13 [chan send]:
bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp.(*clientConn).broadcastErr(0xc420072720, 0x127d880, 0xc4200100e0)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp/conn.go:123 +0x272
bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp.(*clientConn).loop(0xc420072720)
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp/conn.go:51 +0x92
created by bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp.NewClientPipe
        /Users/guillaume/src/gospace/src/bitbucket.x.net/SD/pull/167/vendor/github.com/pkg/sftp/client.go:77 +0x20c

rax    0xe
rbx    0x1296220
rcx    0x7fff5fbff598
rdx    0x7fff5fbff620
rdi    0xf03
rsi    0x1
rbp    0x7fff5fbff5d0
rsp    0x7fff5fbff598
r8     0x7fff5fbff610
r9     0x1
r10    0x0
r11    0x286
r12    0xc4200749b8
r13    0x4
r14    0x0
r15    0xc420074938
rip    0x1054feb
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
```

It seems that broadcastError gets blocked trying to send a result to a channel and thus blocks .Close()

**Comment by eikenb** [comment] 2017-04-22 22:12
My guess at what is going on here is that the server is returning the EOF while there are some packets still being processed. This is valid as it only needs to process the packets in order, not reply in order. But this could cause an issue in the for loop in the Read() method as there are a couple places where it breaks out of the for loop without completely processing the packets inflight.

I'm thinking these break's are wrong. There are breaks in if blocks that break it out of the for loop and there are breaks in the switch statement that do nothing. If I change the breaks to continues it makes more sense as it then processes all packets inFlight before existing the for loop and returning. I'm going to make some test changes in the Read() and push a branch for you to test.

**Comment by eikenb** [comment] 2017-04-22 22:42
I made the changes to Read() and WriteTo() which should cover the uses in your test code. Please checkout the issue167 branch and see if it fixes your problem. Thanks.

**Comment by xiu** [comment] 2017-04-24 07:54
@eikenb just tried your branch, it works perfectly with my test code! Thanks! 
Is there something left to be done before merging this into master?

**Comment by eikenb** [comment] 2017-04-24 17:19
The changes I made were to a pattern of code that is used in almost all the Client methods. I'll need to reproduce my fix in each. It is a fairly trivial change, I just need to make sure to pay attention to a few special cases. I will try, other work permitting, to get to it today and get it merged.

**Comment by eikenb** [comment] 2017-04-24 18:41
"all the Client methods" .. seems this was a bit of an overstatement. The pattern occurs only in the file read/write methods of which there are only the 2 write related ones left.

**Comment by eikenb** [comment] 2017-04-24 20:12
Merged the fixes. You should be good to go now on master.

**Closed by eikenb** 2017-04-24 20:12 UTC
Labels: bug
