### ISSUE TITLE
REALPATH which returns /. causes Cyberduck to error

### ISSUE THREAD

**Issue by LordRalex** [pkg/sftp#207] opened 2017-12-06 02:24 UTC
We have noticed that Cyberduck versions 4-6 (as far as we've tested) do not properly handle the following case when the library returns the following path:

'/.'

Our use-case is in a jailing SFTP, which we use the request-server to handle processing the requests by the clients differently.

We found that when the client requests '.', the library returns "/." (which is not a true absolute path) as the return, then Cyberduck pukes, and we have no way to recover.

Naturally, this used to work before with this library, so something changed within the SFTP library to cause this.

This is the log we got from Cyberduck, pointing to the use of the Realpath being the cause: https://gist.github.com/LordRalex/61b71bfac43232be8ef89068d2495e00

I have found the change which introduced this bug:
https://github.com/pkg/sftp/commit/4d7bb970c49d8a86d12e2cd34952dc80dbc7cb0d#diff-412115c53c6c5fea203e8253f32d2645

In particular, this line of code was removed:
https://github.com/pkg/sftp/commit/4d7bb970c49d8a86d12e2cd34952dc80dbc7cb0d#diff-412115c53c6c5fea203e8253f32d2645L186-189

Before: /. is transformed to /
After: /. is returned to the client

This was a breaking change to the Cyberduck client, and so causes our application to therefore break.

Since /. is not a true absolute path, this code should be re-introduced.

**Comment by puellanivis** [comment] 2017-12-11 17:21
Yeah, it looks like a number of unexpected behavior changes were introduced in that commit. :(

A number of calls that were not wrangling relative paths into absolute paths ended up gaining this behavior.

**Comment by LordRalex** [comment] 2017-12-11 18:16
I know that at least, we had found that Cyberduck breaks because of it, and it took a while to figure out where it came from. 

Since for our mac users we recommend Cyberduck to, this is a critical issue for us. 

It seems like there might need a secondary "cleanToAbs" function which handles cases when it needs to be an Abs, for things like REALPATH. It can branch through cleanPath to clean the path, then resolve it to an Abs.

**Comment by puellanivis** [comment] 2017-12-12 11:46
Indeed, and _super_ helpful how much detail you gave in the issue to begin with. I was able to very quickly zoom in on the code changes and tease out the details.

Yes, I think a cleanToAbs function would be better, but it should resolve the path to an absolute path _first_, then it can branch through cleanPath. This is how the server.go FXP_REALPATH works: (with some significant paraphrasing) `path = filepath.Abs(path); path = filepath.Clean(path); path = filepath.ToSlash(path)`

Following that design would probably work best, and best of all, filepath.Clean(path) already makes sure that `"/."` is fixed to `"/"`, which is why I suggested in the initial pull request that specific ordering of behavior over “make it an absolute path after cleaning”.

**Comment by LordRalex** [comment] 2017-12-12 18:19
The issue with Abs is that it will actually use your local system as a source, so if you send "." to Abs, then it will turn it into the local directory.

So you'd see different behavior compared to server from request-server, which is meant to let you abstract and hide. Server makes sense to do it, but not with request.

Example:
"." -> "/src/github.com/pkg/sftp"

This really isn't something that I would expect request-server to be doing. I would have, and old behavior as well, was that "." -> "/". The clean would remove all of that stuff, then let us mandate what the Abs becomes. I think using the filepath method isn't viable here.

Cleaning it really makes it a Abs EXCEPT when . is being used, and there is no preceding /.
There really is only a few special cases that I am aware of in that regard for it.

**Comment by puellanivis** [comment] 2017-12-13 14:59
Indeed, indeed, I understand your argument LordRalex, but when I said, “turn it into an absolute path” I mostly just meant prepend a "/" to it in RequestServer prior to calling cleanPath.

But then, this causes issues, because maybe now we are duplicating slashes (which is kind of ok, because filepath.Clean should take care of de-duplicating those), but more so, we also have to consider what Windows `filepath` package will do with the code, and ensure that it does the “correct” thing, (whatever that behavior happens to be).

I think this is why they initially changed the code to prepend a "/" if it did not start with one after calling `filepath.ToSlash`, because now that we know it is a slashed path, so we can just append a slash and make it absolute, right? … right? … except properly the path would need to be cleaned again after such a change, which is where and how this bug was introduced.

So this, “cleanToAbs” function should in the common and simple case when `os.Separator` is "/" just prepend a "/" to the start of the given filename if it doesn’t start with one. Once this change has been made _then_ cleanPath is called. This way, the case of "." gets handled properly by the `filepath.Clean` function when it is passed "/.".

But in the complex case… like a Windows absolute path? `filepath.IsAbs` for Windows works with both drive letters and UNC addresses, which I kind of thing is itself a bad idea… So, we want the behavior to work the same across all implementations, right? So that a build on Windows acts the same way as the POSIX case.

So, I think what I’m saying here is, shouldn’t we be using the `path` package instead of the `filepath` one, so that RequestServer is OS-agnostic?

**Comment by LordRalex** [comment] 2017-12-13 15:02
Filepath is already OS-agnostic.

https://golang.org/pkg/path/filepath/#pkg-constants

"The returned path ends in a slash only if it represents a root directory, such as "/" on Unix or `C:\` on Windows."

I've not tested it, but it should already be agnostic. I've not actually used SFTP to a non-masked Windows server, so I do not know how clients even handle that.

**Comment by puellanivis** [comment] 2017-12-13 15:09
“This package does not deal with Windows paths with drive letters or backslashes; to manipulate operating system paths, use the path/filepath package.“ https://golang.org/pkg/path/

`filepath` is _explicitly_ supposed to be a Path-Abstraction-Layer so that code can agnostically handle POSIX and Windows filenames properly.

But RequestServer is supposed to be an abstraction of a filesystem already, and thus not working with “real” OS files, right? Do we really want it to treat the path "C:/" differently depending upon if it is on Windows or POSIX?

**Comment by LordRalex** [comment] 2017-12-13 15:43
Maybe I mis-read your intention of the OS-agnostic. I read it as working with both formats, which filepath does and path doesn't. 

Tried to read the SFTP specs to see how the 2 paths are handled, and it's unclear. I'd be curious then how the lib handles it now then prior to those changes, to see what the old behavior was.

**Comment by puellanivis** [comment] 2017-12-14 11:07
Yeah, no problem. I was meaning more, “should we expect these paths to be automagically different appropriate to the OS that they were build for”, or… like with HTTP handling, do we want to restrict everything to slash paths.

I think in particular the idea that an sftp RequestServer could be treating UNC Windows paths or Plan9 "#filename" absolute paths different would be a bit unsettling for anyone implementing a RequestServer…

Also, even cleaning path requests that contain a backslash… Windows will happily use either kind of slash, and then convert to backslashes, then convert to forward slashes in the ToSlash function, while any POSIX built binary would treat the backslash as a filename character rather than a path character… So, me doing on a client, `scp host:path\\filename .` would do something different if the program had been built for Windows (accessing "./path/filename") or Linux (accessing "./path\\filename").

If we’re accessing the underlying filesystem, then _heck yes_ they should be handling the native path details. But for RequestServer? … this seems much more HTTP-server-like to me. (i.e. referencing abstract filepaths rather than concrete ones.)

**Comment by puellanivis** [comment] 2017-12-14 11:09
Also, to echo eikenb… I would do this, but not sure about contribution processes, and permission of me even really being able to do so from my work. :(

I mean, in my own F/OSS projects, only I can be held responsible, but contributing to other projects without explicit permission? Not a good idea.

Otherwise, I would be on this like hot glue.

**Comment by LordRalex** [comment] 2017-12-14 13:44
I want to then think we need to test what current sftp servers do for
Windows. The spec isn't clear at all, and bitvise actually translates, as
it talks using posix, but maps to windows. It treats /C/ as the c drive.
I'd wonder how others do it, cause if they follow that and clients don't
recognize windows format, that might be the approach needed?

This almost seems like a research point.

**Comment by eikenb** [comment] 2017-12-16 00:10
Just to be clear, the bug that needs to be fixed is that when given '.' it returns '/.' and needs to return '/' and that  is all. The rest has been a more generalized discussion of how to best make sure paths are handled correctly.

I'd like to get this issue fixed in a targeted manner and not get to bogged down in more general refactoring.

**Comment by eikenb** [comment] 2017-12-16 00:33
Adding that and a few more test cases. This seems to do the right thing for all variations.

	func cleanPath(path string) string {
		path = filepath.ToSlash(path)
		if !strings.HasPrefix(path, "/") {
			path = "/" + path
		}
		return filepath.Clean(path)
	}

**Comment by eikenb** [comment] 2017-12-16 01:02
Regarding server functionality on Windows. This is something someone would need to take on. I don't have the time, resources or really the inclination to work on Windows compatibility. But I'll be happy to work with someone who does.

**Comment by puellanivis** [comment] 2017-12-16 13:07
That change is a resolution to this specific narrow bug, but there are still a number of `filepath.ToSlash(filepath.Clean(path))` calls that got changed to using `cleanPath`, which means they have (since the problem commit) started turning paths into absolute paths in this manner.

I will also point out that `path.Abs` does exactly the test we’re looking for before putting a slash at the start, simply because of noting my call that RequestServer should probably be using `path` not `filepath`.

**Comment by puellanivis** [comment] 2017-12-16 13:08
I think the specific handling of files served from the raw system and thus the code in server.go is beyond the scope of the issue. The specific matter at hand is how RequestServer handles paths, and if we should presume that it should be handling paths in an abstract manner à la URLs, or a system specific form?

**Comment by puellanivis** [comment] 2017-12-16 13:11
```
func cleanPath(path string) string {
	path = filepath.ToSlash(path)
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}
	return filepath.Clean(path)
}
```

Unfortunately, on Windows, filepath.Clean() returns a backslash delimited path, even if passed in a forward-slash delimited path. Specifically, it uses the filepath.Separator value to delimit paths, while it uses os.IsPathSeparator to split the path.

**Comment by eikenb** [comment] 2017-12-20 21:13
> [...] which means they have (since the problem commit) started turning paths into absolute paths in this manner.

I assume the problem here is the "in this manner", ie. using this call which uses filepath.Clean(), and not that we are converting everything to absolute paths. I'm going to assume you are, but just to make it clear for the reader I'll say why it doesn't matter. That is that the server has no context for any sort of relative path (the server has no CWD, only the clients have that) and as such the paths are always relative to the root, so converting them to absolute paths is just a normalization/simplification (Clean()ing them).

> The specific matter at hand is how RequestServer handles paths, and if we should presume that it should be handling paths in an abstract manner à la URLs, or a system specific form?
> [..]
> Unfortunately, on Windows, filepath.Clean() returns a backslash delimited path, even if passed in a forward-slash delimited path.

I now see your point and appreciate your taking the time to  re-explain it. I think you are correct that we should move to a `path.Clean()` based version. I think we should convert to the POSIX/URL path (like the path module) based setup internally and it would be up to the Handlers to do any conversion to windows style if needed.

I'm going to leave server.go out of this for now as well. I'm going to leave it as is (as it might work on windows this way), but I'm going to fix the request-* code to convert everything to use strictly POSIX paths internally.

**Comment by eikenb** [comment] 2017-12-20 22:00
I mean for the server.go use of cleanPath() I'm going to change it to use code like I quote above. Which fixes the '/.' issue while maintaining the OS dependent filepath code.

**Comment by eikenb** [comment] 2017-12-20 22:11
Actually scratch that. The original code did not keep things OS dependent, but changed the path to a posix path.

**Comment by eikenb** [comment] 2017-12-20 22:16
So what do you think of just changing cleanPath() to this...

	func cleanPath(p string) string {
		p = filepath.ToSlash(p)
		if !path.IsAbs(p) {
			p = "/" + p
		}
		return path.Clean(p)
	}

That should behave correctly and it passes all tests.

**Comment by LordRalex** [comment] 2017-12-20 22:18
That would pretty much do what the old did, so I see no issues with it.

The unit tests should be updated with the new scenarios as well so this can be avoided in the future.

**Comment by eikenb** [comment] 2017-12-20 22:35
I've added these new tests. Am I missing anything?

+	assert.Equal(t, "/", cleanPath("."))
+	assert.Equal(t, "/", cleanPath("/."))
+	assert.Equal(t, "/a/c", cleanPath("/a/b/../c"))
+	assert.Equal(t, "/a/c", cleanPath("/a/b/../c/"))
+	assert.Equal(t, "/a/b/c", cleanPath("/a/b/c"))

**Comment by LordRalex** [comment] 2017-12-21 06:21
Those seem like good enough tests to me, possibly just a /a/.. resolving to
/ and /a/b/.. to /a might be good, but that really is it.

**Comment by puellanivis** [comment] 2017-12-21 09:41
Thanks for the explanation about why the change in behavior is irrelevant. I was unsure as to how significant the impact of the change of behavior is, I could only just note that it occurred.

The filepath.ToSlash, then path package code is a good choice. 👍

**Closed** 2017-12-21 20:06 UTC
Labels: bug

**Comment by eikenb** [comment] 2017-12-21 20:07
Just pushed the fix. Thanks @LordRalex, @puellanivis.
