### ISSUE TITLE
Incoming packet was garbled on decryption w/ winscp

### ISSUE THREAD

**Issue by Timmmm** [pkg/sftp#132] opened 2016-08-15 11:53 UTC
I'm using [this code](https://gist.github.com/Timmmm/f351605579046d0a225685943e884621). It mostly works, except when copying a large file with WinSCP I get the error "Incoming packet was garbled on decryption" and I have to keep reconnecting.

According to the [WinSCP docs](https://winscp.net/eng/docs/message_incoming_packet_was_garbled_on_decryption) this could be because of miscomputing SSH-2 encryption keys, or ignoring max packet lengths. I tried enabling both workarounds in WinSCP but to no avail.

Entirely possible my code is doing something wrong (I really have very little idea how SSH works; it's mostly copy-pasta). Buuut it could also be a bug in this code, so .... any ideas?

**Comment by Timmmm** [comment] 2016-08-15 12:49
Here's the log from WinSCP.

```
> 2016-08-15 13:41:53.020 9C,24,98,00,00,00,48,89,9C,24,A0,00,00,00,48,8B,9C,24,D0,01,00,00,48,8B,6B,
> 2016-08-15 13:41:53.020 48,48,89,6C,24,58,48,8B,9C,24,D8,01,00,00,48,8B,6B,18,48,89,6C,24,50,48,8D,
> 2016-08-15 13:41:53.020 BC,24,00,01,00,00,0F,57,C0,E8,58,A3,FC,FF,0F,11,47,F8,48,8D,9C,24,00,01,00,
> 2016-08-15 13:41:53.020 00,48,89,1C,24,48,C7,44,24,08,C8,00,00,00,C7,44,24,10,03,00,00,00,E8,3B,A4,
> 2016-08-15 13:41:53.020 FA,FF,48,8D,AC,24,00,01,00,00,48,89,2C,24,48,8B,6C,24,48,48,89,6C,24,08,48,
> 2016-08-15 13:41:53.020 8D,AC,24,98,00,00,00,48,89,6C,24,10,E8,43,A7,FA,FF,0F,B6,5C,24,18,80,FB,00,
> 2016-08-15 13:41:53.020 0F,84,B4,00,00,00,48,8B,9C,24,98,00,00,00,48,89,5C,24,68,48,8B,9C,24,A0,00,
> 2016-08-15 13:41:53.020 00,00,48,89,5C,24,70,C6,44,24,3F,01,48,8B,44,24,48,48,8D,1D,BA,45,4B,00,48,
> 2016-08-15 13:41:53.020 89,1C,24,48,8D,1D,CF,9A,20,00,48,89,9C,24,A8,00,00,00,48,89,5C,24,08,48,89,
> 2016-08-15 13:41:53.020 84,24,B0,00,00,00,48,89,44,24,10,E8,30,D8,08,00,80,7C,24,3F,00,74,36,48,8B,
> 2016-08-15 13:41:53.020 44,24,40,48,8D,1D,FD,45,4B,00,48,89,1C,24,48,8D,1D,D2,FE,29,00,48,89,9C,24,
> 2016-08-15 13:41:53.020 A8,00,00,00,48,89,5C,24,08,48,89,84,24,B0,00,00,00,48,89,44,24,10,E8,F3,D7,
> 2016-08-15 13:41:53.020 08,00,48,8B,5C,24,68,48,89,9C,24,00,02,00,00,48,8B,5C,24,70,48,89,9C,24,08,
> 2016-08-15 13:41:53.020 02,00,00,48,81,C4,C8,01,00,00,C3,48,8D,AC,24,00,01,00,00,48,89,2C,24,48,8B,
> 2016-08-15 13:41:53.020 6C,24,58,48,89,6C,24,08,48,C7,44,24,10,00,00,00,00,E8,5D,A6,FA,FF,0F,B6,5C,
> 2016-08-15 13:41:53.020 24,18,80,FB,00,74,26,48,8B,1D,8C,B4,4B,00,48,89,9C,24,00,02,00,00,48,8B,1D,
> 2016-08-15 13:41:53.020 85,B4,4B,00,48,89,9C,24,08,02,00,00,48,81,C4,C8,01,00,00,C3,48,8D,AC,24,00,
> 2016-08-15 13:41:53.020 01,00,00,48,89,2C,24,48,8B,6C,24,50,48,89,6C,24,08,48,C7,44,24,10,00,00,00,
> 2016-08-15 13:41:53.020 00,E8,09,A6,FA,FF,0F,B6,5C,24,18,80,FB,00,0F,84,8D,00,00,00,31,DB,48,89,9C,
> 2016-08-15 13:41:53.020 24,88,00,00,00,48,89,9C,24,90,00,00,00,48,8D,2D,B2,99,20,00,48,89,2C,24,48,
> 2016-08-15 13:41:53.020 8D,AC,24,88,00,00,00,48,89,6C,24,08,48,8B,6C,24,48,48,89,6C,24,10,E8,32,2B,
> 2016-08-15 13:41:53.020 F7,FF,0F,B6,5C,24,18,80,FB,00,74,24,48,8B,9C,24,88,00,00,00,48,89,5C,24,68,
> 2016-08-15 13:41:53.020 48,8B,9C,24,90,00,00,00,48,89,5C,24,70,C6,44,24,3F,01,E9,7E,FE,FF,FF,48,8B,
> 2016-08-15 13:41:53.020 1D,BD,B4,4B,00,48,89,9C,24,00,02,00,00,48,
. 2016-08-15 13:41:53.023 Sent 32768 bytes
. 2016-08-15 13:41:53.023 There are 0 bytes remaining in the send buffer
. 2016-08-15 13:41:53.023 Looking for network events
. 2016-08-15 13:41:53.023 Detected network event
. 2016-08-15 13:41:53.023 Enumerating network events for socket 1224
. 2016-08-15 13:41:53.023 Enumerated 1 network events making 1 cumulative events for socket 1224
. 2016-08-15 13:41:53.023 Handling network read event on socket 1224 with error 0
. 2016-08-15 13:41:53.023 Received 4 bytes (0)
. 2016-08-15 13:41:53.023 Received 17 bytes (0)
. 2016-08-15 13:41:53.023 Read 4 bytes (17 pending)
. 2016-08-15 13:41:53.023 Read 17 bytes (0 pending)
< 2016-08-15 13:41:53.023 Type: SSH_FXP_STATUS, Size: 17, Number: 186374
< 2016-08-15 13:41:53.023 65,00,02,D8,06,00,00,00,00,00,00,00,00,00,00,00,00,
< 2016-08-15 13:41:53.023 Status code: 0
. 2016-08-15 13:41:53.023 Received 4 bytes (0)
. 2016-08-15 13:41:53.023 Received 17 bytes (0)
. 2016-08-15 13:41:53.023 Read 4 bytes (17 pending)
. 2016-08-15 13:41:53.023 Read 17 bytes (0 pending)
< 2016-08-15 13:41:53.023 Type: SSH_FXP_STATUS, Size: 17, Number: 186630
< 2016-08-15 13:41:53.023 65,00,02,D9,06,00,00,00,00,00,00,00,00,00,00,00,00,
< 2016-08-15 13:41:53.023 Status code: 0
. 2016-08-15 13:41:53.024 Write request offset: 597548, len: 32742
> 2016-08-15 13:41:53.024 Type: SSH_FXP_WRITE, Size: 32764, Number: 188934
> 2016-08-15 13:41:53.035 06,00,02,E2,06,00,00,00,01,33,00,00,00,00,00,09,1E,2C,00,00,7F,E6,8B,1D,B6,
> 2016-08-15 13:41:53.036 B4,4B,00,48,89,9C,24,08,02,00,00,48,81,C4,C8,01,00,00,C3,48,8D,9C,24,00,01,
> 2016-08-15 13:41:53.036 00,00,48,89,1C,24,E8,2D,AA,FA,FF,0F,0B,48,8D,1D,64,FD,29,00,48,89,1C,24,48,
> 2016-08-15 13:41:53.036 8D,1D,79,1E,28,00,48,89,5C,24,08,48,8D,1D,CD,82,4D,00,48,89,5C,24,10,E8,33,
> 2016-08-15 13:41:53.036 AD,F7,FF,48,8B,44,24,18,E9,BB,FC,FF,FF,4D,8D,40,08,4C,89,04,24,48,89,74,24,
> 2016-08-15 13:41:53.036 08,E8,B7,EB,F7,FF,4C,8B,44,24,40,E9,66,FC,FF,FF,41,89,00,E9,18,FC,FF,FF,48,
> 2016-08-15 13:41:53.036 89,0C,24,48,89,6C,24,08,4C,8D,05,C5,3A,21,00,4C,89,44,24,10,E8,9B,AF,F7,FF,
> 2016-08-15 13:41:53.036 0F,0B,48,89,0C,24,48,89,6C,24,08,4C,8D,05,A9,3A,21,00,4C,89,44,24,10,E8,7F,
.....
> 2016-08-15 13:41:53.100 89,8C,24,88,00,00,00,48,8B,44,24,60,48,83,F8,0A,7C,54,48,83,F8,0A,0F,85,9E,
> 2016-08-15 13:41:53.100 03,00,00,48,89,0C,24,48,89,84,24,90,00,00,00,48,89,44,24,08,48,8D,2D,3A,15,
> 2016-08-15 13:41:53.100 30,00,48,89,6C,24,10,48,C7,44,24,18,0A,00,00,00,E8,87,9A,FB,FF,48,8B,8C,24,
> 2016-08-15 13:41:53.100 88,00,00,00,48,8B,84,24,90,00,00,00,48,8B,5C,24,20,48,83,FB,00,0F,8F,54,03,
> 2016-08-15 13:41:53.100 00,00,48,83,F8,04,0F,85,FA,01,00,00,48,89,0C,24,48,89,84,24,90,00,00,00,48,
> 2016-08-15 13:41:53.100 89,44,24,08,48,8D,2D,C6,87,2F,00,48,89,6C,24,10,48,C7,44,24,18,04,00,00,00,
> 2016-08-15 13:41:53.100 E8,C3,98,FB,FF,48,8B,8C,24,88,00,00,00,48,8B,84,24,90,00,00,00,0F,B6,5C,24,
> 2016-08-15 13:41:53.100 20,80,FB,00,0F,84,B1,01,00,00,48,8D,9C,24,C8,00,00,00,48,89,1C,24,E8,A4,79,
> 2016-08-15 13:41:53.100 F6,FF,48,8B,9C,24,C8,00,00,00,31,ED,48,39,
. 2016-08-15 13:41:53.102 Sent 32768 bytes
. 2016-08-15 13:41:53.102 There are 0 bytes remaining in the send buffer
. 2016-08-15 13:41:53.102 Looking for network events
. 2016-08-15 13:41:53.102 Detected network event
. 2016-08-15 13:41:53.102 Enumerating network events for socket 1224
. 2016-08-15 13:41:53.102 Enumerated 1 network events making 1 cumulative events for socket 1224
. 2016-08-15 13:41:53.102 Handling network read event on socket 1224 with error 0
. 2016-08-15 13:41:53.102 Received 4 bytes (0)
. 2016-08-15 13:41:53.102 Received 17 bytes (0)
. 2016-08-15 13:41:53.102 Read 4 bytes (17 pending)
. 2016-08-15 13:41:53.102 Read 17 bytes (0 pending)
< 2016-08-15 13:41:53.102 Type: SSH_FXP_STATUS, Size: 17, Number: 186886
< 2016-08-15 13:41:53.102 65,00,02,DA,06,00,00,00,00,00,00,00,00,00,00,00,00,
< 2016-08-15 13:41:53.102 Status code: 0
. 2016-08-15 13:41:53.103 Received 4 bytes (0)
. 2016-08-15 13:41:53.103 Received 17 bytes (0)
. 2016-08-15 13:41:53.103 Read 4 bytes (17 pending)
. 2016-08-15 13:41:53.103 Read 17 bytes (0 pending)
< 2016-08-15 13:41:53.103 Type: SSH_FXP_STATUS, Size: 17, Number: 187654
< 2016-08-15 13:41:53.103 65,00,02,DD,06,00,00,00,00,00,00,00,00,00,00,00,00,
. 2016-08-15 13:41:53.103 Storing reserved response
. 2016-08-15 13:41:53.103 Waiting for another 4 bytes
. 2016-08-15 13:41:53.103 Looking for incoming data
. 2016-08-15 13:41:53.103 Looking for network events
. 2016-08-15 13:41:53.176 Detected network event
. 2016-08-15 13:41:53.176 Enumerating network events for socket 1224
. 2016-08-15 13:41:53.176 Enumerated 1 network events making 1 cumulative events for socket 1224
. 2016-08-15 13:41:53.176 Handling network read event on socket 1224 with error 0
. 2016-08-15 13:41:53.176 Selecting events 0 for socket 1224
. 2016-08-15 13:41:53.176 Incoming packet was garbled on decryption
. 2016-08-15 13:41:53.178 Connection was lost, asking what to do.
. 2016-08-15 13:41:53.179 Asking user:
. 2016-08-15 13:41:53.179 Incoming packet was garbled on decryption ()
* 2016-08-15 13:41:54.580 (ESshFatal) Incoming packet was garbled on decryption
* 2016-08-15 13:41:54.580 Copying files to remote side failed.
. 2016-08-15 13:41:57.604 --------------------------------------------------------------------------
. 2016-08-15 13:41:57.605 WinSCP Version 5.7.7 (Build 6257) (OS 6.1.7601 Service Pack 1 - Windows 7 Enterprise)
. 2016-08-15 13:41:57.605 Configuration: HKCU\Software\Martin Prikryl\WinSCP 2\
. 2016-08-15 13:41:57.605 Log level: Debug 2

```

**Comment by Timmmm** [comment] 2016-08-16 10:36
I have tried it with [psftp](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html) however, and had no problems. Weird.

**Comment by eikenb** [comment] 2017-01-07 01:15
Based on your comments it sounds like this is some issue with WinSCP acting oddly. If you have the time an inclination to figure out the issue and submit a pull requests with the fix+test I'd be happy to review it. Thanks.

**Comment by LordRalex** [comment] 2017-02-24 01:50
I've been playing around with this library for a custom SFTP server implementation, and I also had this issue pop up when I was using it.

I did a bunch of things, but I changed the sftpWorkerCounter (located https://github.com/pkg/sftp/blob/master/server.go#L21) to be 1, to effectively force a single thread to handle it, and it removed this error.

I'm working on trying to replicate this without my fork of the project (I needed the virtual file system that was added by request-server now, but did not change the ssh connection code).

I did validate this was working with Cygwin's sftp and Filezilla as-is, so it looked like it was some race condition that was occurring with the multiple workers.

**Comment by eikenb** [comment] 2017-02-24 04:12
@LordRalex Thanks for looking into this more and please update us with anything you find. And if you didn't notice the request-server code was merged into master recently.

**Comment by LordRalex** [comment] 2017-02-24 05:00
This is the following test I did to validate that at the very least, this is likely the issue (yay race conditions).

1) Pulled copy of latest version of pkg/sftp (as of this test 14edf2c3f1eef467e8e937cb9ddcff5cc6840828)
2) Ran the examples/sftp-server/main.go file to ensure no code outside of SFTP is involved.
3) Attempted to upload a 170MB tar.gz file to the server.

When the sftpServerWorkerCount is set to 8 (default), WinSCP reports that the packet was garbled after arbitary amounts of data is sent (has ranged from 700k to 2MB, but is never consistent).

When the sftpServerWorkerCount is set to 1, WinSCP is able to fully upload this file to the server with no issues.

Even if I set this value to 2, it will fail.

I have also tested this by using a 200GB file as well to validate that even at 1, it does not produce an error with worker count set to 1.

As a note though, WinSCP seems to upload the file at 50MBps, when using the Cygwin SFTP command will upload at 100MBps.

However, digging into it, I located this Bug Report on WinSCP's tracker which helped locate the (possible) cause.
https://winscp.net/tracker/show_bug.cgi?id=164

Comment #12
2016-05-19 09:21:11
5.8.3: Dynamically increase TCP send buffer on fast connections.

Based on this assumption, I downgraded to a version of WinSCP which was released prior to this date (and was before this issue was opened) as a test. I used 5.7.7 as my version since it was the last non beta/RC release on their sourceforge page.
https://sourceforge.net/projects/winscp/files/WinSCP/5.7.7/ 

Setting the worker count back to 8 allowed for WinSCP to fully upload the original 180MB tar.gz file that I used as my source, along with the 200GB file.

However, updating to 5.8 (any of the beta's) produces this issue, so it's something related with the changelog to 5.8 (located here: http://winscp.net/eng/docs/history_old#5.8)

https://winscp.net/tracker/show_bug.cgi?id=1365 indicates this error, and talks about packets being answered out of order, which might be the problem here, especially since we are talking about what appears to be async operations on sftp with what WinSCP sends.

**Comment by eikenb** [comment] 2017-02-28 00:27
If you figure out what is going on and can come up with a test I'll be happy to look at it. As I don't have access to a windows system and winscp is not cross platform, I can do little to debug this myself.

**Comment by unclejack** [comment] 2017-03-06 15:50
Cyberduck hangs. WinSCP makes the example with SSH and sftp crash due to an interaction of this bug with #169.

**Comment by erikh** [comment] 2017-03-07 09:57
I'm guessing, but I think https://github.com/pkg/sftp/blob/master/server.go#L347 closes the socket as soon as the first error is received, but not after the wait group is finished or the channel is closed. It should probably do that after the wait group finishes / in a signal handler.

Also I have some reservations about https://github.com/pkg/sftp/blob/master/server.go#L363 doing the right thing in all situations but I haven't read enough to prove that.

Not sure if this is useful commentary, but HTH anyway.

**Comment by unclejack** [comment] 2017-03-07 13:21
Addressing those race conditions isn't enough. There are other issues which lead to more race conditions between the handling of the individual packets (e.g. there's a race condition between writing a file and closing that file).

Setting sftpWorkerCount to 1 doesn't make any difference for Cyberduck. Uploads get stuck and never finish. WinSCP fails to create new files. It seems to be able to upload files properly sometimes.

I run into `Error decoding SFTP packet (0, 1, 0).` even with sftpWorkerCount set to 1.

This will need more work.

**Comment by LordRalex** [comment] 2017-03-07 14:28
I was not seeing the WinSCP issue that you experienced where it failed to create files. My testing was done with fresh files to start with, since that was easiest to test at the time and work out a possible fix, so it would create the files I was trying to upload, and it did not have issues.

I have not tried with CyberDuck, but I can test that on my environment and see if I can replicate issues with it.

**Comment by eikenb** [comment] 2017-03-07 19:09
I can confirm that this is reproducible by running WinSCP via wine.

**Comment by eikenb** [comment] 2017-03-07 21:10
If I switch winscp to use blowfish I can't reproduce the garbled packet issue. I do get the "Error decoding SFTP packet (0, 1, 0)." in that case. I'd guess that they are 2 separate issues at this point.

**Comment by eikenb** [comment] 2017-03-07 21:16
Scratch that. I was experimenting with setting the SFTP version as a test of the decoding error and got the garbled packet error again. It took more tries that with AES as the default, but I'm not sure what to do with that.

On the up side, after changing SFTP protocol to 2 I wasn't getting the decoding error. Though I just might not have triggered it yet.

**Comment by unclejack** [comment] 2017-03-07 21:19
We need to take a look at the spec used for SFTP to sort these issues out: https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-6.1

One issue which stands out right now is that we're not handling everything related to the same file sequentially. We also have other problems which need further investigation to sort these issues out.

**Comment by eikenb** [comment] 2017-03-07 21:27
I agree that this is looking like a packet ordering issue. I'll have to look through openssh's sftp client as it doesn't have this issue. It must have some code for dealing with out of order packets or is implemented in a way such that ordering isn't an issue.

I also checked and found that go's ssh library doesn't support blowfish, so changing the cipher type was a red herring. I was just playing with various things people did when they got these issues with other servers to see if anything interesting came from it (so far, not really).

**Comment by eikenb** [comment] 2017-03-07 21:38
With the preferred SFTP protocol set to 3 and the sftpServerWorkerCount set to 1... I have yet to get an error. I've tried about a dozen times uploading a 200M file which up till now has reproduced either the garbled or decoding errors after maybe 3-4 at most (and usually 1 or 2).

So right now it seems that the decoding issue is a problem with the client/server not agreeing on a protocol version and the garbled error is due to packet ordering.

**Comment by unclejack** [comment] 2017-03-07 21:46
I'll test as well and comment here to post my results.

**Comment by eikenb** [comment] 2017-03-07 23:08
I was double checking if the protocol setting in winscp made a differences and it doesn't seem to. Right now, with sftpServerWorkerCount set to 1, I can't get winscp to raise an error even with the preferred sftp protocol set to 6. 

@unclejack I'm thinking the winscp issue only occurs due to ordering issues when you have sftpServerWorkerCount > 1, like @LordRalex reported. Can you recheck the code with sftpServerWorkerCount set to 1 and no other changes to see if you can reproduce it. If you can please describe anything you can think of that might be different.

The only changes from before are my tests (vs earlier today) was I changed the EOF handling code in the example server a bit (this has been pused) and my current code has additional debug() entries and it built with the debug build tag (this is not pushed).

**Comment by unclejack** [comment] 2017-03-07 23:11
@eikenb Can you publish that as a gist, please? I'd like to test both the current code with sftpServerWorkerCount=1 and your patch.

**Comment by eikenb** [comment] 2017-03-07 23:46
I just the upload in a loop 125 times using winscp's command line support and it uploaded fine every time. This was with sftpServerWorkerCount=1.

@unclejack I just pushed a branch named issue132 that has all my current changes. None of them are meant to go in master, they are just for testing.

**Comment by eikenb** [comment] 2017-03-08 01:00
To maintain ordering of replies will require a way to keep track of packet order and a short list/array to queue up reply packets in. The list will need to be the same length as the sftpServerWorkerCount as that is the max the incoming and outgoing could get out of sync. The packet ID should work for the packet ordering, though I'm not 100% on this. I don't see anyplace in the spec where it says they packet IDs need to be order-able, though both winscp and openssh's sftp client use incrementing integers for packet IDs.

**Comment by eikenb** [comment] 2017-03-08 02:24
Packet IDs won't work as while they are very predictable from openssh's sftp, they aren't from others I've tested. We'd need to mark them internally.

**Comment by eikenb** [comment] 2017-03-09 18:50
Removed the note about packet-ids not being good because I think they will work for the initial implementation.

**Comment by unclejack** [comment] 2017-03-09 20:46
I apologize for the delayed reply.

pkg/sftp with sftpServerWorkerCount=1 and no other changes:
A few uploads via WinSCP worked just fine without any issue. I didn't encounter any error.

I've tried to use WinSCP's "New file" feature to create a new remote file with some text in it. It was disconnected and it failed to create the file.

Cyberduck failed to upload any file at all. I could get it to upload by closing the SSH+sftp server and letting Cyberduck reconnect after the restart. I think this may have simply performed the upload as the first operation without any file listing operations.


pkg/sftp with sftpServerWorkerCount=1 and the changes from the issue132 branch:
WinSCP stopped working after a few uploads.

"New file" is also not working with WinSCP.

Cyberduck couldn't upload any files. I had to close the SFTP server and restart it. Cyberduck seemed to be able to upload only when the first command was the upload. Anything else blocks the upload forever.

**Comment by eikenb** [comment] 2017-03-10 23:02
Fun twist. It doesn't seem that ordering is the problem. I added outgoing packet synchronization code that makes sure all packets go out in the same order they came in based on the packet id. I have it spewing debug output that verifies that it is sending them in order but I still am getting both (at different times) the "garbled on decryption" error and the "decoding SFTP packet" error.

I'm going to dig into the winscp code a bit to see if that sheds any light on things.

**Comment by eikenb** [comment] 2017-03-10 23:27
Both errors seem to result from lengths being off...

The garbled error seems to be raised from this snippet.

    /*
     * _Completely_ silly lengths should be stomped on before they
     * do us any more damage
     */
    if (st->len < 0 || st->len > OUR_V2_PACKETLIMIT || st->len % st->cipherblk != 0) {
        bombout(("Incoming packet length field was garbled"));

The decoding error comes from this snippet (SFTP_PACKET_ERROR is the decoding error).

    inline void Need(unsigned int Size)
    {
      if (Size > RemainingLength)
      {
        throw Exception(FMTLOAD(SFTP_PACKET_ERROR, (int(FPosition), int(Size), int(FLength))));
      }
    }

**Comment by eikenb** [comment] 2017-03-11 00:37
Just wanted to note that winscp and the server are properly negotiating protocol version 3. Found the dialog in winscp that says what protocol it is using to talk to current server.

**Comment by eikenb** [comment] 2017-03-11 05:10
I think this might be a bad interaction between winscp and the ssh library. I can find no issues with the sftp protocol or handling. The packets are flowing just fine then suddenly the client hangs up the connection and displays one of the errors. The garbled error definitely comes out of the putty code and the decoding one doesn't make sense at the packet level. 

I looked into trying to find an scp server using the go ssh lib to see if it would replicate the problem, but none of the servers provide the necessary functionality (both exec and shell support, as winscp uses ssh shell for file lists and such).

Anyways, unless someone else can find something on this issue I think the best choice is just to recommend using different window SFTP clients. I'd suggest filezilla for a GUI and putty's psftp command for scripting/automation. They both work without issue.

**Comment by unclejack** [comment] 2017-03-11 10:13
We could try to use the standalone sftp server together with openssh to check if the ssh code is indeed the issue.

I'll try to test and post here again to discuss the results.

**Comment by unclejack** [comment] 2017-03-11 21:17
I've tried to use the standalone_server together with OpenSSH. Directory listing and changing the directory seems to work.

I always get this error from WinSCP:
```
Permission denied.
Error code: 3
Error message from server: operation not permitted
```

Cyberduck is also not able to upload files.

**Comment by unclejack** [comment] 2017-03-12 00:25
The standalone server works properly when used together with OpenSSH. Cyberduck and WinSCP seem happy as well.

It seems it's related to the Go SSH implementation or to the SSH code from the example server. pkg/sftp seems to be OK with a single worker when used together with the standalone server.

The standalone server has a bug related to the read only mode. That's going to be a small patch.

**Comment by eikenb** [comment] 2017-03-12 23:46
Great idea to try the standalone server as the backend for openssh's sftp server. I was able to reproduce both the garbled and decoding errors with this setup, which means it isn't the Go ssh library at fault and it must be a problem in this package. I also tried with the packet synchronizing patch I wrote and the problem persists with it as well.

So the issue related to having >1 worker, but it is not related to packet ordering. It seems to be related to the size of the packet's data segment as both errors are related to size.

**Comment by eikenb** [comment] 2017-03-13 00:30
I was reviewing the packets coming in and out at the lowest level I could w/o digging into the underlying networking libraries and kept seeing that the errors still always occurred after packets were sent out of order. So I plugged in my packet syncing patch again and found that it wasn't doing a 100% job of keeping the packets in order. Sometimes a packet would come in, get processed, and sent back out before the packet ordered before it even reaches the system. My syncing code was based on the idea that the packets would arrive in sequence and get out of order while being processed.

I think I can tweak my current syncing code to maintain a minimal queue of packets to make sure earlier packets arrive before later ones are sent. I'm trying this now.



and caught a packet being sent out of order with my packet syncing code in place. The packet syncing code

**Comment by eikenb** [comment] 2017-03-13 04:43
The problem with my packet syncing code is that it uses the ID field which isn't available until to late in the incoming packet handling process. After the unmarshalling which is already in the worker pool so it is to late to make sure they get registered in order. I'm going to have to bite the bullet and add an internal count/order field to the packets.

**Comment by eikenb** [comment] 2017-03-13 21:54
I tested my idea by pulling the unmarshalling code out of the worker and to the top server.Serve() loop. This let me track by request id and I'm happy to report it worked. I was able to run winscp with the normal 8 workers with no errors. Did it in a loop 134 times before I decided good enough.

I went this way after starting on the internal counter and seeing what a pain it would be to add. So I think I'm going to try to stick with the request-id as long as having it done pre-worker doesn't impact throughput. My intuition is that the unmarshalling code being done pre-worker won't have any real impact on performance but I'll run a few benchmarks to test it as I can. I'd much prefer to use request-ids as adding a counter would require lots of changes to propagate them through the system.

**Comment by eikenb** [comment] 2017-03-13 22:41
Note I'm going to create a new branch for the real work now that I think I have a handle on how I'm going to fix it. I pushed my last round of test code to branch issue132 and will leave it for now as I created it mainly to convey my tests to those interested. I'll clean up when this is all done.

**Comment by unclejack** [comment] 2017-03-14 00:00
I'll review the code and comment in a few hours. Please let me know if there's anything you'd like me to do in addition to that.

**Comment by eikenb** [comment] 2017-03-14 02:45
When looking at the issue132 branch be generous as it is pretty messy and was mainly just a way to give an idea of what I was trying. I threw together the last commit in whatever state it was at the time as I had figured out what to do. I think it fails a couple of the integration tests.

I've started working on the version I'll merge and will push it once I've got it mostly done for people to try out. Hopefully by tomorrow.

**Comment by eikenb** [comment] 2017-03-15 02:45
I've uploaded the initial version that I plan on merging into master in the packet-ordering branch. I think I need to do one minor revision due to the fact that I used the new sort.Slice(), which is 1.8 only and I'd like to maintain a bit of backwards compatibility.

**Comment by eikenb** [comment] 2017-03-15 03:35
Ok. 1.7 compatible fix pushed. Please take a look at the "packet-ordering" branch and give it a try. I haven't been able to reproduce either the garbled or decoded errors with it. Ran a few benchmarks as well and it didn't seem to have any effect on throughput (at least as they measured it).

Assuming nobody finds anything wrong with it I'll merge this in a day or 2.

**Comment by unclejack** [comment] 2017-03-15 13:52
@eikenb: I've sent PR #171 to fix the issue with the standalone server.

I'll test and review all the code now.

**Comment by unclejack** [comment] 2017-03-15 15:05
I've taken a look at the changes from the new branch.

I've compiled the example SSH+SFTP server. I've tried to use it with Cyberduck, but the upload hangs as it did before.
It's not entirely clear what's breaking Cyberduck. It needs to be investigate further. However, I can't tell whether it's related to this issue or not.
Perhaps it'd be a good idea to figure out if we can get some dumps somehow.

WinSCP has uncovered a race condition so far:
```
Write at 0x00c4202085a0 by goroutine 18:
  os.(*file).close()
      /usr/local/go/src/os/file_unix.go:143 +0x124
  os.(*File).Close()
      /usr/local/go/src/os/file_unix.go:132 +0x55
  github.com/pkg/sftp.(*Server).closeHandle()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:54 +0x18a
  github.com/pkg/sftp.handlePacket()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:214 +0x251e
  github.com/pkg/sftp.(*Server).sftpServerWorker()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:151 +0x146
  github.com/pkg/sftp.(*Server).Serve.func1()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:291 +0x64

Previous read at 0x00c4202085a0 by goroutine 12:
  os.(*File).pwrite()
      /usr/local/go/src/os/file_unix.go:275 +0x50
  os.(*File).WriteAt()
      /usr/local/go/src/os/file.go:166 +0xbd
  github.com/pkg/sftp.handlePacket()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:273 +0x2aad
  github.com/pkg/sftp.(*Server).sftpServerWorker()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:151 +0x146
  github.com/pkg/sftp.(*Server).Serve.func1()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:291 +0x64

Goroutine 18 (running) created at:
  github.com/pkg/sftp.(*Server).Serve()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:294 +0xef
  main.main()
      /home/unclejack/code/sftp-server/server.go:140 +0xc4a

Goroutine 12 (running) created at:
  github.com/pkg/sftp.(*Server).Serve()
      /home/unclejack/go/src/github.com/pkg/sftp/server.go:294 +0xef
  main.main()
      /home/unclejack/code/sftp-server/server.go:140 +0xc4a
```

I've tested with a few big files and WinSCP seems to work.

As a side note, I think the example server still needs some changes to make it more robust. It exits when the client exits. This is a different behavior of the OpenSSH daemon used together with SFTP. The SSH daemon keeps running to allow another client to connect.
I'll look into this issue soon.

**Comment by eikenb** [comment] 2017-03-15 19:54
@unclejack What did you do to get that race with winscp? With the changes in the packet-ordering branch I've not been able to get winscp to produce any errors.

**Comment by eikenb** [comment] 2017-03-15 20:03
Looking at the traceback I think I know what is going on. It is another bug related to this one. I was going to open another ticket about it as it is really about the sftp library not being compliant with the spec rather than a problem with winscp.

The problem is that the spec dictates in [section-7](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-7) that the packets don't have to be sent to the client in order (winscp is out of spec here) _but_ they have to be processed in order. The worker pool doesn't guarantee that the packets  will be processed in order. This was done to get throughput on transferring large files (packet order doesn't matter for read/write) at the cost of possible issues with non-transferring commands.

The fix I was considering was to change the server to use a simple state machine about whether to use a pool of workers or a single worker. It would use a single worker for all non-transferring commands and pool for uploads/downloads. It would need to be a state machine to enforce things like waiting for the upload/download pool to finish before processing the Close command (ie. your traceback).

**Comment by eikenb** [comment] 2017-03-15 20:07
I'd like to close this issue and file separate issue for the sec-7 spec issue and the Cyberduck issue. I'd like to keep this one about diagnosing the weird winscp errors and what the problem was (even if it wasn't the final fix).

So unless you can reproduce the original "Incoming packet was garbled on decryption"  or the "Error decoding SFTP packet (0, 1, 0)" error, I'd like to consider this issue closed.

**Comment by unclejack** [comment] 2017-03-15 21:11
@eikenb: That's reasonable.

**Comment by eikenb** [comment] 2017-03-16 00:51
@unclejack Thanks for all your feedback on this ticket. Thanks to @LordRalex and @Timmmm as well.

**Comment by eikenb** [comment] 2017-03-25 22:59
Just merged the packet-ordering branch which fixes both the "Incoming packet was garbled on decryption" and the "Error decoding SFTP packet (0, 1, 0)" errors.

**Closed by eikenb** 2017-03-25 22:59 UTC
