### ISSUE TITLE
Upload of big file panics or does not upload whole file

### ISSUE THREAD

**Issue by dsbrng25b** [pkg/sftp#154] opened 2017-01-24 23:58 UTC
I try to upload a big file to an sftp server. After sending about 2GB of the file my programm panics or returns successfully but has not transfered the whole file. I'm able to reproduce the problem by sending 3GB from /dev/zero (see code below).
I tested this on a linux vm:
* Linux localhost.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* go version go1.7.4 linux/amd64
* OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013

From sshd i get the following errors:
```
...
dispatch_protocol_error: type 123 seq 327094
Disconnecting: Invalid ssh2 packet type: 217
debug1: do_cleanup
debug1: PAM: cleanup
debug1: PAM: closing session
pam_unix(sshd:session): session closed for user root
debug1: PAM: deleting credentials
error: getsockname failed: Bad file descriptor
```
Test code:
```golan
package main

import (
    "io"
    "log"
    "github.com/pkg/sftp"
    "golang.org/x/crypto/ssh"
    "os"
)


func main(){
    user := "root"
    password := "test"
    host := "127.0.0.1:22"
    config := &ssh.ClientConfig{
        User: user,
        HostKeyCallback: nil,
        Auth: []ssh.AuthMethod{
            ssh.Password(password),
        },
    }
    config.SetDefaults()
    sshConn, err := ssh.Dial("tcp", host, config)
    if err != nil {
        log.Fatal("connection failed", err)
    }
    defer sshConn.Close()

    client, err := sftp.NewClient(sshConn)
    if err != nil {
        log.Fatal("failed to create sftp client: ", err)
    }

    dstFile, err := client.Create("/tmp/testfile")
    if err != nil {
        log.Fatal(err)
    }
    defer dstFile.Close()

    srcFile, err := os.Open("/dev/zero")
    if err != nil {
        log.Fatal(err)
    }
    bytes, err := io.Copy(dstFile, io.LimitReader(srcFile, 3e9))
    //bytes, err := dstFile.ReadFrom(srcFile)
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("successfully written %d bytes\n", bytes)
}
```
The panic i get sometimes:
```
panic: ssh: no key material for msgNewKeys

goroutine 6 [running]:
panic(0x572620, 0xc42000dce0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
golang.org/x/crypto/ssh.(*connectionState).writePacket(0xc42000a668, 0xc4200163c0, 0x667540, 0xc4200105a0, 0xc420362240, 0x9, 0x9, 0x0, 0x0)
        /root/go/src/golang.org/x/crypto/ssh/transport.go:163 +0x226
golang.org/x/crypto/ssh.(*transport).writePacket(0xc42000a600, 0xc420362240, 0x9, 0x9, 0x0, 0x0)
        /root/go/src/golang.org/x/crypto/ssh/transport.go:144 +0x77
golang.org/x/crypto/ssh.(*handshakeTransport).pushPacket(0xc420082000, 0xc420362240, 0x9, 0x9, 0x0, 0x0)
        /root/go/src/golang.org/x/crypto/ssh/handshake.go:211 +0x51
golang.org/x/crypto/ssh.(*handshakeTransport).kexLoop(0xc420082000)
        /root/go/src/golang.org/x/crypto/ssh/handshake.go:291 +0x303
created by golang.org/x/crypto/ssh.newClientTransport
        /root/go/src/golang.org/x/crypto/ssh/handshake.go:118 +0x2bb
exit status 2
```

**Comment by eikenb** [comment] 2017-02-01 04:09
Your panic looks like this bug... https://github.com/golang/go/issues/18850

**Comment by eikenb** [comment] 2017-02-01 04:23
This almost smells like the old 2g filesystem limit on 32bit OSs. Doing a quick grep there are lots of uint32 types in the sftp lib. Bet one of those is tracking file offset or something.

**Comment by belak** [comment] 2017-02-01 09:32
That panic can happen when enough data is transferred for the ssh lib to request a rekey... reverting to an older version of go/crypto should fix that.

We're currently running golang/crypto@2f8be38b9a7533b8763d48273737ff6e90428a96 in prod without this issue.

**Comment by dsbrng25b** [comment] 2017-02-09 19:17
@belak thank you for the hint, with the commit of golang/crypto you mentioned it does also work for me. i was surprised that most of the time my program finished successful even if it didn't send all the data. if you transfer files with your productive program, do you any further checks to be sure that the whole file has been transferred completely (e.g. checking if the transferred bytes are equal to the file size or checksum)?

**Comment by belak** [comment] 2017-02-09 19:41
They also supposedly fixed this on the master branch of golang/crypto but I don't know the commit.

**Comment by eikenb** [comment] 2017-02-12 20:33
Fix on master was ... 
https://github.com/golang/crypto/commit/77014cf7f9bde4925afeed52b7bf676d5f5b4285

**Comment by eikenb** [comment] 2017-02-18 21:29
Are you still able to reproduce the 2G file cutoff? I am unable. Running the provided code (only modified to use my public key for local auth) I get a 3000000000 byte file created every time. I'm pretty sure I was able to reproduce this before. Maybe it was caused by an upstream crypto library bug that has been fixed?

**Comment by eikenb** [comment] 2017-02-18 21:55
> Maybe it was caused by an upstream crypto library bug that has been fixed?

Looks like this is the case. I pulled the crypto/ssh library version that would have been on master when you submitted this bug and I was able to reproduce it again.

I tracked it down, and it seems this was fixed by crypto commit: https://github.com/golang/crypto/commit/641ab6b32049cabca26c30bf27baaae445bf4175

It isn't obvious to me what fixed it in that commit and I don't really have the time to track it down. If you (or anyone else) are curious enough and do, please post a description here.

**Closed by eikenb** 2017-02-18 21:55 UTC
